Projeto de Análise da planilha de vendas de um e-commerce fictício.

In [101]:
import pandas as pd
import plotly.express as px

tabela = pd.read_csv("/home/andreas/Programação/Projetos Python/Análise de Dados/Linked/vendas_linked_ps.csv")

display(tabela)

base_color = ["green"]

,order_id,order_date,product_category,product_name,quantity,unit_price,total_value,customer_region,payment_method,order_status
0,ORD-0001,2024-01-01,Eletrônicos,Cabo HDMI 2m,1,41.17,41.17,Nordeste,Cartao,Entregue
1,ORD-0002,2024-01-01,Beleza,Pinceis de Maquiagem Kit 12pc,1,86.09,86.09,Sul,Cartao,Entregue
2,ORD-0003,2024-01-01,Esportes,Tênis de Corrida Nike,1,410.93,410.93,Sudeste,Cartao,Entregue
3,ORD-0004,2024-01-01,Esportes,Tapete de Yoga 6mm,2,72.96,145.92,Sul,PIX,Entregue
4,ORD-0005,2024-01-02,Beleza,Pinceis de Maquiagem Kit 12pc,1,74.26,74.26,Sudeste,PIX,Entregue
...,...,...,...,...,...,...,...,...,...,...
1195,ORD-1196,2024-12-31,Esportes,Bicicleta Speed Aro 29,2,1374.83,2749.66,Centro-Oeste,Boleto,Cancelado
1196,ORD-1197,2024-12-31,Moda,Calça Jeans Skinny,1,134.24,134.24,Centro-Oeste,Cartao,Entregue
1197,ORD-1198,2024-12-31,Esportes,Bicicleta Speed Aro 29,1,1432.56,1432.56,Sudeste,Cartao,Entregue
1198,ORD-1199,2024-12-31,Casa e Jardim,Vassoura Elétrica Robô,2,452.23,904.46,Nordeste,Boleto,Entregue
1199,ORD-1200,2024-12-31,Esportes,Garrafa Térmica 1L,1,55.62,55.62,Sudeste,Cartao,Entregue

In [102]:
# Verificando se a tabela tem valores nulos

display(tabela.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          1200 non-null   object
 1   order_date        1200 non-null   object
 2   product_category  1200 non-null   object
 3   product_name      1200 non-null   object
 4   quantity          1200 non-null   int64
 5   unit_price        1200 non-null   float64
 6   total_value       1200 non-null   float64
 7   customer_region   1200 non-null   object
 8   payment_method    1200 non-null   object
 9   order_status      1200 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 93.9+ KB

None

In [103]:
tabela.describe()

# Valor médio de vendas: R$ 185,36

# Menor valor de produto: R$ 26,28

# Maior valor de produto: R$ 1635,01

          quantity   unit_price  total_value
count  1200.000000  1200.000000  1200.000000
mean      1.720833   185.368233   312.699400
std       1.006849   270.472143   521.207179
min       1.000000    26.280000    26.280000
25%       1.000000    53.297500    84.187500
50%       1.000000   118.295000   159.870000
75%       2.000000   187.597500   329.155000
max       5.000000  1635.010000  7407.350000

In [104]:
display(tabela["product_category"].value_counts())

# INFO

# Categoria mais vendida de produtos por quantidade: beleza e moda
# Categoria menos vendida de produtos por quantidade: livros

# Categorias mais vendidas por valor: esportes e eletrônicos
# Categoria menos vendida por valor: livros

# Regiões com mais vendas: Sudeste e Nordeste.
# Regiões com menos vendas: Norte e Centro-Oeste.

# INSIGHT 1: promover a venda de livros por meio de um evento ou oferecendo um desconto.  

# INSIGHT 2: promover o marketing voltado às regiões com menos clientes com foco em aquisição de clientes.




# Verificando a quantidade vendida por tipo de produto: 

print("Divisão por categoria:")
tabelaProd = tabela.groupby("product_category")["total_value"].sum().reset_index()
tabelaProd = tabelaProd.sort_values("total_value")

display(tabelaProd)


# Gráfico tipo de produto vs valor em receita

graficoCategoria = px.bar(tabelaProd, x='product_category', y='total_value', color="product_category", color_discrete_sequence = [base_color])

graficoCategoria.show()




print("-"*200)
print(" "*50)


# Verificando a quantidade vendida por região: 

print("Divisão por regiões:")
tabelaRegion = tabela.groupby("customer_region")["total_value"].sum().reset_index()
tabelaRegion = tabelaRegion.sort_values("total_value")

display(tabelaRegion)


# Gráfico região vs valor em receita:

graficoCategoria = px.bar(tabelaRegion, x='customer_region', y='total_value', color="customer_region", color_discrete_sequence = [base_color])

graficoCategoria.show()

product_category
Beleza           224
Moda             219
Eletrônicos      201
Esportes         191
Casa e Jardim    186
Livros           179
Name: count, dtype: int64

Divisão por categoria:

  product_category  total_value
4           Livros     21391.34
0           Beleza     45174.01
5             Moda     49014.31
1    Casa e Jardim     72498.69
2      Eletrônicos     91820.69
3         Esportes     95340.24

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Divisão por regiões:

  customer_region  total_value
2           Norte     29534.82
0    Centro-Oeste     37098.86
4             Sul     65468.84
1        Nordeste    103201.93
3         Sudeste    139934.83

In [105]:
tabelaItem = tabela.groupby(["product_name", "product_category"])["total_value"].sum().reset_index()

tabelaItem = tabelaItem.sort_values("total_value", ascending=False)


# Itens mais vendidos

print("Produtos mais vendidos:")
display(tabelaItem.head(10))




# Gráfico itens mais vendidos vs valor em receita:

graficoCategoriaMais = px.bar(tabelaItem.head(10), x='product_name', y='total_value', color="product_name", color_discrete_sequence = [base_color])

graficoCategoriaMais.show()


print("-"*200)
print(" "*50)



# Itens menos vendidos

print("Produtos menos vendidos:")
display(tabelaItem.tail(10))

# Gráfico itens menos vendidos vs valor em receita:

graficoCategoriaMenos = px.bar(tabelaItem.tail(10), x='product_name', y='total_value', color="product_name", color_discrete_sequence = [base_color])

graficoCategoriaMenos.show()

Produtos mais vendidos:

                      product_name product_category  total_value
2           Bicicleta Speed Aro 29         Esportes     64718.12
31   Smartphone Samsung Galaxy A54      Eletrônicos     46019.67
37          Vassoura Elétrica Robô    Casa e Jardim     31804.71
24         Perfume Masculino 100ml           Beleza     13562.13
23      Panela de Pressão Elétrica    Casa e Jardim     13076.46
36           Tênis de Corrida Nike         Esportes     12749.18
29  Secador de Cabelo Profissional           Beleza     11834.06
39            Webcam Full HD 1080p      Eletrônicos     11819.48
34       Teclado Mecânico Redragon      Eletrônicos     11771.12
3          Bolsa Feminina de Couro             Moda     10616.98

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Produtos menos vendidos:

                    product_name product_category  total_value
8         Carregador Turbo USB-C      Eletrônicos      2777.24
30    Shampoo Antirresíduo 300ml           Beleza      2652.22
22            Pai Rico Pai Pobre           Livros      2416.14
10          Corda de Pular Speed         Esportes      2373.68
0               A Startup Enxuta           Livros      2297.60
28  Sapiens - Uma Breve Historia           Livros      2118.39
5                   Cabo HDMI 2m      Eletrônicos      1866.33
21             O Poder do Hábito           Livros      1536.95
19              Meia Kit 3 pares             Moda      1481.64
27          Regador de Jardim 5L    Casa e Jardim      1394.70

In [106]:
# Tabela dos métodos de pagamento vs valor em receita:

tabelaPayment = tabela.groupby("payment_method")["total_value"].sum().reset_index()

display(tabelaPayment)


# Gráfico dos métodos de pagamento vs valor em receita:

graficoPayment = px.pie(tabelaPayment, values='total_value', names='payment_method')

graficoPayment.show()




# INFO:
# Maior quantidade de receita é recebida por mei ode cartão e pix.

  payment_method  total_value
0         Boleto     53935.78
1         Cartao    180324.81
2            PIX    140978.69

In [107]:
tabelaCancel = tabela.groupby("order_status")["total_value"].sum().reset_index()

display(tabelaCancel)

# Porcentagem de cancelamentos

graficoCancel = px.bar(tabelaCancel, x='total_value', y='order_status', color='order_status', color_discrete_sequence = [base_color])

graficoCancel.show()


# INFO

# Valor total das compras canceladas: R$ 38.367,13. 
# INSIGHT 3: É um valor muito alto. Uma possível abordagem seria enviar um e-mail oferecendo um desconto quando a compra for cancelada.

  order_status  total_value
0    Cancelado     38367.13
1  Em transito     39957.24
2     Entregue    296914.91

In [118]:
tabelaCancelReg = tabela.groupby("customer_region")["order_status"].value_counts().reset_index()

# Total por região

total_regiao = tabelaCancelReg.groupby("customer_region")["count"].sum()


# Só os cancelados

cancelados = tabelaCancelReg[tabelaCancelReg["order_status"] == "Cancelado"].set_index("customer_region")["count"]


# Porcentagem de cancelamentos

porcentagem = (cancelados / total_regiao * 100).round(2).reset_index()
porcentagem.columns = ["customer_region", "cancelamento_%"]
porcentagem = porcentagem.sort_values("cancelamento_%", ascending=False)
display(porcentagem)


# Porcentagem de cancelamentos por região

graficoCancelReg = px.bar(porcentagem, x='customer_region', y='cancelamento_%', color_discrete_sequence = [base_color])

graficoCancelReg.show()


#INFO

# INSIGHT 4: A região sul é a terceira com menos clientes e a primeira na porcentagem de cancelamentos. Possivelmente fazer uma campanha de descontos. Verificar causas (como prazos de entrega e frete, por exemplo) e trabalhar em cima da informação obtida. Possivelmente fazer uma campanha de frete grátis, por exemplo, mas é necessário entender o porquê dos cancelamentos.

  customer_region  cancelamento_%
4             Sul           14.69
0    Centro-Oeste           13.95
1        Nordeste           11.11
3         Sudeste            7.58
2           Norte            6.40

In [109]:
tabelaCancProd = tabela.groupby(["product_category"])["order_status"].value_counts().reset_index()

# display(tabelaCancProd)

total_categoria = tabelaCancProd.groupby("product_category")["count"].sum()

cancelados = tabelaCancProd[tabelaCancProd["order_status"] == "Cancelado"].set_index("product_category")["count"]

porcentagem = (cancelados / total_categoria * 100).round(2).reset_index()
porcentagem.columns = ["product_category", "cancelamento_%"]
porcentagem = porcentagem.sort_values("cancelamento_%", ascending=False)
display(porcentagem)

# Nenhuma informação importante aqui neste ponto

  product_category  cancelamento_%
5             Moda           12.33
2      Eletrônicos           11.44
0           Beleza           10.27
1    Casa e Jardim            9.68
4           Livros            9.50
3         Esportes            8.90