Projeto de Análise da planilha de vendas de um e-commerce fictício.

In [2]:
import pandas as pd

tabela = pd.read_csv("/home/andreas/Programação/Projetos Python/Análise de Dados/Linked/vendas_linked_ps.csv")

display(tabela)

,order_id,order_date,product_category,product_name,quantity,unit_price,total_value,customer_region,payment_method,order_status
0,ORD-0001,2024-01-01,Eletrônicos,Cabo HDMI 2m,1,41.17,41.17,Nordeste,Cartao,Entregue
1,ORD-0002,2024-01-01,Beleza,Pinceis de Maquiagem Kit 12pc,1,86.09,86.09,Sul,Cartao,Entregue
2,ORD-0003,2024-01-01,Esportes,Tênis de Corrida Nike,1,410.93,410.93,Sudeste,Cartao,Entregue
3,ORD-0004,2024-01-01,Esportes,Tapete de Yoga 6mm,2,72.96,145.92,Sul,PIX,Entregue
4,ORD-0005,2024-01-02,Beleza,Pinceis de Maquiagem Kit 12pc,1,74.26,74.26,Sudeste,PIX,Entregue
...,...,...,...,...,...,...,...,...,...,...
1195,ORD-1196,2024-12-31,Esportes,Bicicleta Speed Aro 29,2,1374.83,2749.66,Centro-Oeste,Boleto,Cancelado
1196,ORD-1197,2024-12-31,Moda,Calça Jeans Skinny,1,134.24,134.24,Centro-Oeste,Cartao,Entregue
1197,ORD-1198,2024-12-31,Esportes,Bicicleta Speed Aro 29,1,1432.56,1432.56,Sudeste,Cartao,Entregue
1198,ORD-1199,2024-12-31,Casa e Jardim,Vassoura Elétrica Robô,2,452.23,904.46,Nordeste,Boleto,Entregue
1199,ORD-1200,2024-12-31,Esportes,Garrafa Térmica 1L,1,55.62,55.62,Sudeste,Cartao,Entregue

In [ ]:
# Verificando se a tabela tem valores nulos

display(tabela.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          1200 non-null   object
 1   order_date        1200 non-null   object
 2   product_category  1200 non-null   object
 3   product_name      1200 non-null   object
 4   quantity          1200 non-null   int64
 5   unit_price        1200 non-null   float64
 6   total_value       1200 non-null   float64
 7   customer_region   1200 non-null   object
 8   payment_method    1200 non-null   object
 9   order_status      1200 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 93.9+ KB

None

In [ ]:
tabela.describe()

# Valor médio de vendas: R$ 185,36

# Menor valor de produto: R$ 26,28

# Maior valor de produto: R$ 1635,01

          quantity   unit_price  total_value
count  1200.000000  1200.000000  1200.000000
mean      1.720833   185.368233   312.699400
std       1.006849   270.472143   521.207179
min       1.000000    26.280000    26.280000
25%       1.000000    53.297500    84.187500
50%       1.000000   118.295000   159.870000
75%       2.000000   187.597500   329.155000
max       5.000000  1635.010000  7407.350000

In [ ]:
display(tabela["product_category"].value_counts())


# Categoria mais vendida de produtos: beleza e moda
# Categoria menos vendida de produtos: livros


# INSIGHT 1: oferecer mais livros sobre beleza e moda. 



# Verificando a quantidade vendida por tipo de produto: 

tabela = tabela.groupby("product_category")["total_value"].sum()

display(tabela)

# Verificando a quantidade vendida por região: 

tabela = tabela.groupby("customer_region")["total_value"].sum()

display(tabela)

product_category
Beleza           224
Moda             219
Eletrônicos      201
Esportes         191
Casa e Jardim    186
Livros           179
Name: count, dtype: int64

product_category
Beleza           45174.01
Casa e Jardim    72498.69
Eletrônicos      91820.69
Esportes         95340.24
Livros           21391.34
Moda             49014.31
Name: total_value, dtype: float64

customer_region
Centro-Oeste     37098.86
Nordeste        103201.93
Norte            29534.82
Sudeste         139934.83
Sul              65468.84
Name: total_value, dtype: float64

In [ ]:
# Itens mais vendidos

tabela = tabela.groupby("product_name")["total_value"].sum()
# tabela.sort_values("total_value")

display(tabela)

KeyError: 'Column not found: total_value'